services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config
    ports:
      - 1080:80
      - 1443:443
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
    external: true
