services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "6080:8080"
    volumes:
      - ./home:/var/jenkins_home
    networks:
      - proxy-network
  ssh-agent:
    image: jenkins/ssh-agent
    container_name: jenkins_ssh

networks:
  proxy-network:
    name: proxy-network
    external: true
